server:
  port: 3080
management:
  port: 3081
  address: 127.0.0.1
  add-application-context-header: false

multipart:
  max-file-size: 20MB
  max-request-size: 20MB

spring:
  profiles.active: local
  application.name: 'initial'
  mvc.throw-exception-if-no-handler-found: true
  jpa:
    show_sql: true
    database: MYSQL
    generate_ddl: false


jdbc:
  master:
    driver_class_name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xiaowu?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    initial_size: 1
    max_idle: 10
    test_on_borrow: true
    validation_query: select 1

